use std::error::Error;

mod aoc_2018;

fn main() -> Result<(), Box<dyn Error>> {
    // aoc_2018::day_01::part_1::run()?;
    Ok(())
}
